### ISSUE TITLE
Infinite loop when using --strictMode 

### ISSUE THREAD

**Issue by benwh** [zaggino/z-schema#90]
When I attempt to validate any schema using the command-line tool with the --strictMode option (or any of the --forceX options or --noTypeless) the tools just prints out `request: http://json-schema.org/draft-04/schema - 200` repeatedly.

Is this expected behaviour?

Example, using https://raw.githubusercontent.com/zaggino/z-schema/master/benchmark/advanced_schema_v4.json

    $ z-schema --strictMode advanced_schema_v4.json
    request: http://json-schema.org/draft-04/schema - 200
    request: http://json-schema.org/draft-04/schema - 200
    request: http://json-schema.org/draft-04/schema - 200
    request: http://json-schema.org/draft-04/schema - 200
    ...

**Comment by zaggino** [comment]
Fixed in latest version:
```
npm info publish z-schema@3.4.3
npm info ok
```

**Comment by benwh** [comment]
Thanks for the quick turnaround, issue resolved for me.

It's interesting to note though that the above example still fails, because `http://json-schema.org/draft-04/schema` doesn't conform to the strict checks, so I'm not sure how useful this parameter is!

**Comment by zaggino** [comment]
Strict checks are checks over the specification of `json-schema` but useful in real world applications. For example with `strictMode` you can't have strings in schema without `maxLength` to avoid getting very large strings posted against your api, but normal `json-schema` doesn't require you to specify `maxLength`. See more about this in README
